import { Navbar } from '@/components';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import type { ReactNode } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
	return (
		<html lang='en'>
			<body
				className={`${inter.className} bg-dark bg-[url("/assets/images/Shapes.png")] bg-right-top bg-no-repeat `}
			>
				<Navbar />
				{children}
			</body>
		</html>
	);
}
