export { default as Navbar } from '@/components/Navbar/Navbar';
export { default as Hero } from '@/components/Hero/Hero';
export { default as FeaturedCompany } from '@/components/FeaturedCompany/FeaturedCompany';
export { default as Statistic } from '@/components/Statistic/Statistic';
export { default as FinancialSnapshot } from '@/components/FinancialSnapshot/FinancialSnapshot';
export { default as CustomizableAssets } from '@/components/CustomizableAssets/CustomizableAssets';
export { default as Features } from '@/components/Features/Features';
export { default as NumbersData } from '@/components/NumbersData/NumbersData';
export { default as Testimonial } from '@/components/Testimonial/Testimonial';
